# Generated by Django 6.1 on 2026-09-13 11:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(default=1, verbose_name='日程番号')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日付')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='日程タイトル・テーマ')),
                ('memo', models.TextField(blank=True, verbose_name='その日のメモ')),
            ],
            options={
                'verbose_name': '日程',
                'verbose_name_plural': '日程一覧',
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='TravelStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='巡回順')),
                ('name', models.CharField(max_length=200, verbose_name='スポット名')),
                ('category', models.CharField(choices=[('sightseeing', '観光・絶景'), ('gourmet', 'グルメ・カフェ'), ('hotel', '宿泊（ホテル・宿）'), ('activity', 'アクティビティ・体験'), ('transport', '交通拠点（駅・空港・港）'), ('other', 'その他スポット')], default='sightseeing', max_length=30, verbose_name='カテゴリ')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='住所')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='緯度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='経度')),
                ('google_place_id', models.CharField(blank=True, max_length=200, verbose_name='Google Place ID')),
                ('photo_url', models.URLField(blank=True, max_length=1000, verbose_name='写真URL')),
                ('photo_image', models.ImageField(blank=True, null=True, upload_to='travel/stops/', verbose_name='アップロード写真')),
                ('arrival_time', models.TimeField(blank=True, null=True, verbose_name='到着予定時刻')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='出発予定時刻')),
                ('stay_duration', models.CharField(blank=True, max_length=50, verbose_name='滞在予定時間')),
                ('memo', models.TextField(blank=True, verbose_name='スポットメモ・予約情報')),
                ('transport_mode', models.CharField(choices=[('car', '🚗 車 / レンタカー'), ('train', '🚃 電車 / 新幹線'), ('flight', '✈️ 飛行機'), ('bus', '🚌 バス'), ('walk', '🚶 徒歩'), ('boat', '🚢 船・フェリー')], default='car', max_length=20, verbose_name='次のスポットへの移動手段')),
                ('transport_departure_time', models.TimeField(blank=True, null=True, verbose_name='移動出発時刻')),
                ('transport_arrival_time', models.TimeField(blank=True, null=True, verbose_name='移動到着時刻')),
                ('transport_time_text', models.CharField(blank=True, max_length=100, verbose_name='所要時間目安')),
                ('transport_memo', models.CharField(blank=True, max_length=300, verbose_name='便名・列車名・座席メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='travel.travelday', verbose_name='日程')),
            ],
            options={
                'verbose_name': '立ち寄りスポット',
                'verbose_name_plural': '立ち寄りスポット一覧',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TravelTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='旅行タイトル')),
                ('destination', models.CharField(blank=True, max_length=120, verbose_name='主な旅行先・エリア')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='開始日')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='終了日')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='travel/covers/', verbose_name='カバー写真')),
                ('cover_preset', models.CharField(choices=[('hokkaido', '北海道・自然'), ('kyoto', '京都・古都'), ('okinawa', '沖縄・リゾートビーチ'), ('tokyo', '東京・アーバン夜景'), ('fuji', '富士山・温泉')], default='hokkaido', max_length=50, verbose_name='プリセット写真')),
                ('description', models.TextField(blank=True, verbose_name='旅行のテーマ・メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_travel_trips', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('members', models.ManyToManyField(blank=True, related_name='travel_trips', to=settings.AUTH_USER_MODEL, verbose_name='参加メンバー')),
            ],
            options={
                'verbose_name': '旅行',
                'verbose_name_plural': '旅行一覧',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='travelday',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='travel.traveltrip', verbose_name='旅行'),
        ),
        migrations.AlterUniqueTogether(
            name='travelday',
            unique_together={('trip', 'day_number')},
        ),
    ]
