# Generated by Django 6.1 on 2026-09-13 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelStopPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='travel/stop_photos/', verbose_name='写真')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='写真のメモ・キャプション')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='travel.travelstop', verbose_name='対象スポット')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_stop_photos', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'verbose_name': 'スポット写真',
                'verbose_name_plural': 'スポット写真一覧',
                'ordering': ['-created_at'],
            },
        ),
    ]
