# Generated by Django 6.1 on 2026-09-13 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_travelstopphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelstop',
            name='paired_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_from', to='travel.travelstop', verbose_name='連動スポット'),
        ),
    ]
