# Generated by Django 6.1 on 2026-09-23 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_travelstop_paired_stop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='ニックネーム')),
                ('avatar_color', models.CharField(default='#0284C7', max_length=20, verbose_name='アバター色')),
                ('avatar_icon', models.CharField(choices=[('traveler', 'バックパッカー'), ('camera', 'フォトグラファー'), ('plane', 'ジェットセッター'), ('car', 'ロードトリッパー'), ('train', '鉄道マニア'), ('camp', 'キャンパー'), ('food', 'グルメ探訪家'), ('relax', '温泉・癒やし')], default='traveler', max_length=30, verbose_name='アバターアイコン')),
                ('bio', models.TextField(blank=True, verbose_name='自己紹介・旅スタイル')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='メール認証完了')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='認証完了日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_profile', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'たびしおプロフィール',
                'verbose_name_plural': 'たびしおプロフィール一覧',
            },
        ),
    ]
