# Generated by Django 6.1 on 2026-09-22 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodscan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='記録日')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='当日体重(kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '日別食事ログ',
                'verbose_name_plural': '日別食事ログ一覧',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GeneralFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='食品・料理名')),
                ('category', models.CharField(choices=[('staple', '主食 (ご飯・パン・麺)'), ('main', '主菜 (肉・魚・卵・大豆)'), ('side', '副菜 (野菜・サラダ・海藻)'), ('soup', '汁物 (味噌汁・スープ)'), ('udon', 'うどんメニュー (讃岐)'), ('snack', '間食・デザート・飲料')], default='staple', max_length=20)),
                ('serving_size', models.CharField(default='1人前', max_length=100, verbose_name='目安量')),
                ('calories', models.FloatField(verbose_name='エネルギー(kcal)')),
                ('protein', models.FloatField(default=0.0, verbose_name='たんぱく質(g)')),
                ('fat', models.FloatField(default=0.0, verbose_name='脂質(g)')),
                ('carbohydrates', models.FloatField(default=0.0, verbose_name='炭水化物(g)')),
                ('salt', models.FloatField(default=0.0, verbose_name='食塩相当量(g)')),
                ('icon', models.CharField(default='fa-utensils', max_length=50, verbose_name='アイコン')),
            ],
            options={
                'verbose_name': '一般料理マスタ',
                'verbose_name_plural': '一般料理マスタ一覧',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', '朝食'), ('lunch', '昼食'), ('dinner', '夕食'), ('snack', '間食・夜食')], max_length=20)),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_entries', to='foodlog.dailylog')),
            ],
            options={
                'verbose_name': '食事区分',
                'verbose_name_plural': '食事区分一覧',
                'unique_together': {('daily_log', 'meal_type')},
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='食品・料理名')),
                ('serving_amount', models.FloatField(default=1.0, verbose_name='数量(倍率)')),
                ('serving_unit', models.CharField(default='人前', max_length=50, verbose_name='単位')),
                ('calories', models.FloatField(default=0.0, verbose_name='カロリー(kcal)')),
                ('protein', models.FloatField(default=0.0, verbose_name='たんぱく質(g)')),
                ('fat', models.FloatField(default=0.0, verbose_name='脂質(g)')),
                ('carbohydrates', models.FloatField(default=0.0, verbose_name='炭水化物(g)')),
                ('salt', models.FloatField(default=0.0, verbose_name='食塩相当量(g)')),
                ('image_url', models.URLField(blank=True, default='', max_length=1000, verbose_name='写真URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_meals', to='foodscan.fooditem')),
                ('meal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='foodlog.mealentry')),
            ],
            options={
                'verbose_name': '食事品目明細',
                'verbose_name_plural': '食事品目明細一覧',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='ゲストダイエッター', max_length=50, verbose_name='ニックネーム')),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性')], default='male', max_length=10, verbose_name='性別')),
                ('birth_year', models.IntegerField(default=1995, verbose_name='生年')),
                ('height', models.FloatField(default=170.0, verbose_name='身長(cm)')),
                ('current_weight', models.FloatField(default=65.0, verbose_name='現在の体重(kg)')),
                ('target_weight', models.FloatField(default=62.0, verbose_name='目標体重(kg)')),
                ('activity_level', models.CharField(choices=[('sedentary', '低い (デスクワーク中心・運動少なめ)'), ('moderate', '普通 (立ち仕事・軽い運動あり)'), ('active', '高い (活発な運動・肉体労働)')], default='moderate', max_length=20, verbose_name='身体活動レベル')),
                ('goal_type', models.CharField(choices=[('maintain', '現状維持 (体重キープ)'), ('lose_slow', 'ゆるやか減量 (-0.5〜1kg/月)'), ('lose_fast', 'しっかり減量 (-1〜2kg/月)'), ('muscle', '筋肉量アップ・増量')], default='lose_slow', max_length=20, verbose_name='ダイエット目標')),
                ('target_calories', models.FloatField(default=2000.0, verbose_name='目標カロリー(kcal)')),
                ('target_p_ratio', models.FloatField(default=20.0, verbose_name='目標たんぱく質比率(%)')),
                ('target_f_ratio', models.FloatField(default=25.0, verbose_name='目標脂質比率(%)')),
                ('target_c_ratio', models.FloatField(default=55.0, verbose_name='目標炭水化物比率(%)')),
                ('target_salt', models.FloatField(default=7.5, verbose_name='目標塩分上限(g)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foodlog_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザー栄養目標',
                'verbose_name_plural': 'ユーザー栄養目標一覧',
            },
        ),
    ]
