# Generated by Django 6.1 on 2026-08-30 01:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店舗名')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('lat', models.FloatField(default=34.3427, verbose_name='緯度')),
                ('lng', models.FloatField(default=134.0465, verbose_name='経度')),
                ('place_id', models.CharField(blank=True, max_length=150, verbose_name='Google Place ID')),
                ('featured_menu', models.CharField(blank=True, max_length=150, verbose_name='名物メニュー')),
                ('price_range', models.CharField(default='300円〜700円', max_length=50, verbose_name='価格帯')),
                ('opening_hours', models.CharField(blank=True, max_length=150, verbose_name='営業時間')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='shops/', verbose_name='店舗写真')),
                ('photo_url', models.CharField(blank=True, max_length=500, verbose_name='写真URL')),
                ('description', models.TextField(blank=True, verbose_name='店舗紹介・メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'うどん店舗',
                'verbose_name_plural': 'うどん店舗一覧',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='讃岐うどん巡礼2026', max_length=150, verbose_name='旅行タイトル')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('is_public', models.BooleanField(default=True, verbose_name='公開設定')),
                ('memo', models.TextField(blank=True, verbose_name='旅行メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_trips', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': 'うどん旅',
                'verbose_name_plural': 'うどん旅一覧',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='会員さん', max_length=50, verbose_name='投稿者名')),
                ('author_avatar_color', models.CharField(default='#D99B26', max_length=20, verbose_name='アバター色')),
                ('author_avatar_icon', models.CharField(default='👩', max_length=10, verbose_name='アバター絵文字')),
                ('score_noodle', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='麺のコシ・喉ごし')),
                ('score_soup', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='出汁の風味・旨味')),
                ('score_atmosphere', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='店の雰囲気・情緒')),
                ('score_tempura', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='天ぷらのサクサク度')),
                ('score_cost', models.PositiveSmallIntegerField(default=9, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='コスパ・満足度')),
                ('score_total', models.DecimalField(decimal_places=1, default=4.8, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='総合評価')),
                ('comment', models.TextField(blank=True, verbose_name='レビューコメント')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='レビュー写真')),
                ('photo_url', models.CharField(blank=True, max_length=500, verbose_name='写真URL')),
                ('stamp_type', models.CharField(choices=[('讃岐人選', '讃岐人選'), ('名店認定', '名店認定'), ('巡礼完了', '巡礼完了'), ('絶品百選', '絶品百選')], default='讃岐人選', max_length=30, verbose_name='認定スタンプ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='udon.shop', verbose_name='対象店舗')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='udon.trip', verbose_name='うどん旅')),
            ],
            options={
                'verbose_name': 'うどんレビュー',
                'verbose_name_plural': 'うどんレビュー一覧',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='会員さん', max_length=50, verbose_name='メンバー名')),
                ('avatar_color', models.CharField(default='#D99B26', max_length=20, verbose_name='アバター背景色')),
                ('avatar_icon', models.CharField(default='👩', max_length=10, verbose_name='アバターアイコン')),
                ('role', models.CharField(choices=[('owner', '主催者'), ('member', 'メンバー')], default='member', max_length=20, verbose_name='役割')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='udon.trip', verbose_name='旅行')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_memberships', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '参加メンバー',
                'verbose_name_plural': '参加メンバー一覧',
            },
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_order', models.PositiveIntegerField(default=1, verbose_name='巡回順')),
                ('scheduled_time', models.TimeField(blank=True, null=True, verbose_name='予定時間')),
                ('travel_time_text', models.CharField(default='車で18分', max_length=50, verbose_name='所要時間・ステータス')),
                ('status', models.CharField(choices=[('planned', '予定'), ('visited', '訪問済'), ('skipped', 'スキップ')], default='planned', max_length=20, verbose_name='訪問ステータス')),
                ('notes', models.TextField(blank=True, verbose_name='備考・注文予定')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_stops', to='udon.shop', verbose_name='店舗')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='udon.trip', verbose_name='旅行')),
            ],
            options={
                'verbose_name': '巡回ストップ',
                'verbose_name_plural': '巡回ストップ一覧',
                'ordering': ['visit_order'],
                'unique_together': {('trip', 'visit_order')},
            },
        ),
    ]
