# Generated by Django 6.1 on 2026-08-30 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author_avatar_icon',
            field=models.CharField(default='会', max_length=10, verbose_name='アバターアイコン'),
        ),
        migrations.AlterField(
            model_name='tripmember',
            name='avatar_icon',
            field=models.CharField(default='会', max_length=10, verbose_name='アバターアイコン'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='ニックネーム')),
                ('avatar_color', models.CharField(default='#E67E22', max_length=20, verbose_name='アバターカラー')),
                ('avatar_icon', models.CharField(default='udonchu', max_length=50, verbose_name='アバタータイプ')),
                ('favorite_udon', models.CharField(default='釜玉うどん', max_length=50, verbose_name='好みのうどん')),
                ('level_title', models.CharField(default='見習いうどん人', max_length=50, verbose_name='うどん人称号')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'うどん人プロフィール',
                'verbose_name_plural': 'うどん人プロフィール一覧',
            },
        ),
    ]
