# Generated by Django 6.1 on 2026-08-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udon', '0003_userprofile_avatar_image_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='google_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Google評価'),
        ),
        migrations.AddField(
            model_name='shop',
            name='google_user_ratings_total',
            field=models.IntegerField(default=0, verbose_name='Google口コミ件数'),
        ),
    ]
