# Generated by Django 6.1 on 2026-09-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udon', '0005_trip_date_alter_trip_end_date_alter_trip_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stamp_type',
            field=models.CharField(choices=[('香川人選', '香川人選'), ('名店認定', '名店認定'), ('巡礼完了', '巡礼完了'), ('絶品百選', '絶品百選')], default='香川人選', max_length=30, verbose_name='認定スタンプ'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='title',
            field=models.CharField(default='香川うどん巡礼2026', max_length=150, verbose_name='旅行タイトル'),
        ),
    ]
