# Generated by Django 6.1 on 2026-09-05 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udon', '0006_alter_review_stamp_type_alter_trip_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='会員さん', max_length=50, verbose_name='投稿者名')),
                ('image', models.ImageField(upload_to='shop_photos/', verbose_name='店舗写真')),
                ('caption', models.CharField(blank=True, max_length=150, verbose_name='写真メモ・説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='udon.shop', verbose_name='対象店舗')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_photos', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'verbose_name': '店舗写真',
                'verbose_name_plural': '店舗写真一覧',
                'ordering': ['-created_at'],
            },
        ),
    ]
