# Generated by Django 6.1 on 2026-09-22 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='バーコード(JAN/EAN)')),
                ('name', models.CharField(max_length=255, verbose_name='商品名')),
                ('brand', models.CharField(blank=True, default='', max_length=255, verbose_name='メーカー・ブランド')),
                ('category', models.CharField(blank=True, default='', max_length=255, verbose_name='カテゴリ')),
                ('image_url', models.URLField(blank=True, default='', max_length=1000, verbose_name='商品画像URL')),
                ('serving_size', models.CharField(blank=True, default='100g', max_length=100, verbose_name='内容量/基準単位')),
                ('calories', models.FloatField(blank=True, null=True, verbose_name='エネルギー (kcal)')),
                ('protein', models.FloatField(blank=True, null=True, verbose_name='たんぱく質 (g)')),
                ('fat', models.FloatField(blank=True, null=True, verbose_name='脂質 (g)')),
                ('carbohydrates', models.FloatField(blank=True, null=True, verbose_name='炭水化物 (g)')),
                ('sugar', models.FloatField(blank=True, null=True, verbose_name='糖質 (g)')),
                ('fiber', models.FloatField(blank=True, null=True, verbose_name='食物繊維 (g)')),
                ('salt', models.FloatField(blank=True, null=True, verbose_name='食塩相当量 (g)')),
                ('ingredients', models.TextField(blank=True, default='', verbose_name='原材料名')),
                ('allergens', models.CharField(blank=True, default='', max_length=500, verbose_name='アレルゲン (カンマ区切り)')),
                ('source', models.CharField(choices=[('openfoodfacts', 'Open Food Facts'), ('user', 'ユーザー登録'), ('manual', '手動登録')], default='openfoodfacts', max_length=30, verbose_name='データ取得元')),
                ('scan_count', models.PositiveIntegerField(default=1, verbose_name='スキャン回数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '食品データ',
                'verbose_name_plural': '食品データ一覧',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='スキャン日時')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='foodscan.fooditem', verbose_name='対象食品')),
            ],
            options={
                'verbose_name': 'スキャン履歴',
                'verbose_name_plural': 'スキャン履歴一覧',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
