# Generated by Django 6.1 on 2026-09-24 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='カテゴリ名')),
                ('slug', models.SlugField(unique=True, verbose_name='スラッグ')),
                ('item_type', models.CharField(choices=[('all', '共通'), ('product', '新発売・新商品'), ('event', 'イベント・フェス')], default='all', max_length=10, verbose_name='対象種別')),
                ('icon', models.CharField(default='🍽️', max_length=50, verbose_name='アイコン（絵文字）')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ一覧',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('product', '新発売・新商品'), ('event', 'グルメイベント・催事')], db_index=True, default='product', max_length=10, verbose_name='情報種別')),
                ('title', models.CharField(max_length=200, verbose_name='商品名 / イベント名')),
                ('brand', models.CharField(help_text='例: セブン-イレブン, マクドナルド, 実行委員会', max_length=120, verbose_name='メーカー / ブランド / 主催')),
                ('catchphrase', models.CharField(blank=True, help_text='魅力が一言で伝わる短文', max_length=250, verbose_name='キャッチコピー・見出し')),
                ('description', models.TextField(verbose_name='詳細・特徴説明')),
                ('price_info', models.CharField(blank=True, help_text='例: 380円(税込), 入場無料(飲食代別途)', max_length=100, verbose_name='価格・入場料')),
                ('area_info', models.CharField(blank=True, help_text='例: 全国, 関東・東海限定, 東京都渋谷区', max_length=150, verbose_name='販売地域 / 開催エリア')),
                ('venue_name', models.CharField(blank=True, help_text='イベントの場合の会場名（例: 代々木公園 イベント広場）', max_length=150, verbose_name='会場名・開催場所')),
                ('venue_address', models.CharField(blank=True, max_length=250, verbose_name='会場住所')),
                ('start_date', models.DateField(db_index=True, verbose_name='発売日 / 開催開始日')),
                ('end_date', models.DateField(blank=True, help_text='未定または通年販売の場合は空欄', null=True, verbose_name='販売終了予定日 / 開催終了日')),
                ('is_period_limited', models.BooleanField(default=False, verbose_name='期間限定 / 数量限定')),
                ('image', models.ImageField(blank=True, null=True, upload_to='food/images/%Y/%m/', verbose_name='アップロード画像')),
                ('image_url', models.URLField(blank=True, help_text='画像ファイルアップロードの代わりにURL直接指定も可能', max_length=500, verbose_name='画像URL (外部参照)')),
                ('official_url', models.URLField(blank=True, max_length=500, verbose_name='公式サイト / 参照URL')),
                ('tags', models.CharField(blank=True, help_text='例: 秋限定, 栗, 濃厚, 話題の新作', max_length=200, verbose_name='タグ (カンマ区切り)')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='注目・ピックアップ')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='公開フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='food.foodcategory', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': '食ニュース・イベント',
                'verbose_name_plural': '食ニュース・イベント一覧',
                'ordering': ['-is_featured', 'start_date', '-created_at'],
            },
        ),
    ]
