# Generated by Django 6.1 on 2026-09-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='記事タイトル')),
                ('url', models.URLField(db_index=True, max_length=1000, unique=True, verbose_name='記事URL')),
                ('source_name', models.CharField(db_index=True, max_length=100, verbose_name='配信元メディア')),
                ('category', models.CharField(choices=[('new_product', '新商品・新発売'), ('sweets', 'スイーツ・アイス'), ('fastfood', '外食・ファストフード'), ('convenience', 'コンビニ'), ('event', 'イベント・催事・フェス'), ('drinks', 'カフェ・お酒・飲料'), ('noodle', 'ラーメン・麺類'), ('trend', 'トレンド・話題')], db_index=True, default='new_product', max_length=30, verbose_name='カテゴリ')),
                ('summary', models.TextField(blank=True, verbose_name='要約・本文抜粋')),
                ('image_url', models.URLField(blank=True, max_length=1000, verbose_name='サムネイル画像URL')),
                ('published_at', models.DateTimeField(db_index=True, verbose_name='配信日時')),
                ('keyword_query', models.CharField(blank=True, max_length=100, verbose_name='収集キーワード')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='注目記事')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='収集日時')),
            ],
            options={
                'verbose_name': 'Web収集食ニュース',
                'verbose_name_plural': 'Web収集食ニュース一覧',
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='foodentry',
            options={'ordering': ['-is_featured', 'start_date', '-created_at'], 'verbose_name': '特集・ピックアップ食情報', 'verbose_name_plural': '特集・ピックアップ食情報一覧'},
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='area_info',
            field=models.CharField(blank=True, max_length=150, verbose_name='販売地域 / 開催エリア'),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='brand',
            field=models.CharField(max_length=120, verbose_name='メーカー / ブランド / 主催'),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='catchphrase',
            field=models.CharField(blank=True, max_length=250, verbose_name='キャッチコピー・見出し'),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='販売終了予定日 / 開催終了日'),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='画像URL (外部参照)'),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='price_info',
            field=models.CharField(blank=True, max_length=100, verbose_name='価格・入場料'),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='tags',
            field=models.CharField(blank=True, max_length=200, verbose_name='タグ (カンマ区切り)'),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='venue_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='会場名・開催場所'),
        ),
    ]
